### ISSUE TITLE
Not able to run on iOS simulator

### ISSUE THREAD

**Issue by ludy-auror** [amorenew/record_mp3_plus#1]
Hi @amorenew, thanks for maintaining this awesome package. I can see you've added support for MacOS target, I am wondering does it support running on iOS simulator?

When I am running on a iOS simulator on my M2 Macbook Pro, I got this error:

> ld: building for 'iOS-simulator', but linking in object file (.pub-cache/hosted/pub.dev/record_mp3_plus-1.1.0/ios/Classes/Fat-Lame/lib/libmp3lame.a[arm64][2](VbrTag.o)) built for 'iOS'
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thanks

record_mp3_plus version: 1.1.0
Machine: M2 Macbook Pro
MacOS: 14.2.1 Sonoma
XCode: 15.3

**Comment by amorenew** [comment]
Check my pod file where I exclude architecture arm64 or x86
The pod file in example/ios
For my Intel Mac I exclude arm and it works for me so fir m2 I think you need to exclude x86

**Comment by amorenew** [comment]
either this
`config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "x86_64"`
or that
`config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"`

**Comment by ludy-auror** [comment]
@amorenew Thanks. I added both `EXCLUDED_ARCHS` lines to my Podfile, but I am getting another error for another third party library I'm using which can't compile without that arm64 arch.

I'm thinking of compiling `libmp3lame.a` by myself, maybe something is missing in the archive? Let me know I'm heading the right direction?

**Comment by amorenew** [comment]
You can't put both of them, one of them but I don't know which one

**Comment by amorenew** [comment]
You can't put both of them, one of them but I don't know which one

**Comment by ludy-auror** [comment]
Thanks for your help
I solved the issue by clearing my pod cache, now I can run it on iOS simulator. Previously I could only run on physical iOS device


For future reference, here's what I did

1. Add line `config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"` to `Podfile`, like this:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
...
```
2. Delete `ios/Pods` folder, delete `Podfile.lock`, re-run `pod install --repo-update`
3. Run your app from flutter, it should be able to run on an iOS simulator now

**Comment by maxzod** [comment]
@ludy-auror , adding that line caused this error for shared prefs , path provider and other packages 

```
User-Defined Issue (Xcode): Unsupported Swift architecture
```

**Comment by amorenew** [comment]
@maxzod it depends on your machine 
https://github.com/amorenew/record_mp3_plus/issues/1#issuecomment-2179927454

**Comment by maxzod** [comment]
indeed i use m2 😢

**Comment by Erichain** [comment]
> Thanks for your help I solved the issue by clearing my pod cache, now I can run it on iOS simulator. Previously I could only run on physical iOS device
> 
> For future reference, here's what I did
> 
> 1. Add line `config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"` to `Podfile`, like this:
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>     target.build_configurations.each do |config|
>       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
>     end
> ...
> ```
> 
> 2. Delete `ios/Pods` folder, delete `Podfile.lock`, re-run `pod install --repo-update`
> 3. Run your app from flutter, it should be able to run on an iOS simulator now

Oh god! Thanks for your answer, I finally can run my app on simulator 😭
